# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 822339e5667cbf14731eae86c681ac032123fc7fc58f843ae0450b717618c90abe7cac948186af937c1a7e44afc836854f5e69d4ae087f11225605b1c3fba47e

test:
  secret_key_base: 7fb3341ce7b94cbd3d8535067e82a025e854929c4bef2c0643e0386c07e6f0c0e306be55ecdc8ddf376f6170a8f823755b78db34afb32e511492d7e093e1755f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
